# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-22 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, 'vip'), (3, 'svip')], default=1),
        ),
    ]
