# Generated by Django 3.0.1 on 2019-12-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('birthday', models.DateField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
