# Generated by Django 3.0.1 on 2020-01-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rear', '0002_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
