# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-18 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campuses',
            options={'verbose_name': '校区信息', 'verbose_name_plural': '校区信息'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name': '班级信息', 'verbose_name_plural': '班级信息'},
        ),
        migrations.AlterModelOptions(
            name='consultrecord',
            options={'verbose_name': '跟进记录', 'verbose_name_plural': '跟进记录'},
        ),
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'verbose_name': '合同信息', 'verbose_name_plural': '合同信息'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户信息', 'verbose_name_plural': '客户信息'},
        ),
    ]
